"""与 run_16_seed_nav_capability.sql 一致；库表无数据时兜底。"""

from typing import List, Tuple

# (code, title, nav_item_code, group_label)
CAPABILITY_FALLBACK: Tuple[Tuple[str, str, str, str], ...] = (
    ("order.filter.customer", "订单列表：按客户筛选", "order", "订单"),
    ("order.filter.status", "订单列表：按状态筛选", "order", "订单"),
    ("order.filter.payment_type", "订单列表：按付款类型筛选", "order", "订单"),
    ("order.filter.keyword", "订单列表：关键词搜索", "order", "订单"),
    ("order.action.create", "订单：新建", "order", "订单"),
    ("order.action.edit", "订单：编辑", "order", "订单"),
    ("order.action.delete", "订单：删除", "order", "订单"),
    (
        "customer_product.filter.customer",
        "客户产品列表：按客户筛选",
        "customer_product",
        "客户产品",
    ),
    (
        "customer_product.filter.keyword",
        "客户产品列表：关键词搜索",
        "customer_product",
        "客户产品",
    ),
    (
        "customer_product.action.create",
        "客户产品：新建",
        "customer_product",
        "客户产品",
    ),
    ("customer_product.action.edit", "客户产品：编辑", "customer_product", "客户产品"),
    (
        "customer_product.action.delete",
        "客户产品：删除",
        "customer_product",
        "客户产品",
    ),
    (
        "customer_product.action.import",
        "客户产品：Excel 导入",
        "customer_product",
        "客户产品",
    ),
    (
        "customer_product.action.export_template",
        "客户产品：下载导入模板",
        "customer_product",
        "客户产品",
    ),
    ("delivery.filter.customer", "送货列表：按客户筛选", "delivery", "送货"),
    ("delivery.filter.status", "送货列表：按状态筛选", "delivery", "送货"),
    ("delivery.filter.keyword", "送货列表：关键词搜索", "delivery", "送货"),
    ("delivery.action.create", "送货：新建送货单", "delivery", "送货"),
    ("delivery.action.detail", "送货：详情", "delivery", "送货"),
    ("delivery.action.print", "送货：打印", "delivery", "送货"),
    ("delivery.action.mark_shipped", "送货：标记已发", "delivery", "送货"),
    ("delivery.action.mark_created", "送货：标记待发", "delivery", "送货"),
    ("delivery.action.mark_expired", "送货：标记失效", "delivery", "送货"),
    ("delivery.action.delete", "送货：删除", "delivery", "送货"),
    ("delivery.action.clear_waybill", "送货：清空快递单号", "delivery", "送货"),
    (
        "delivery.action.edit_delivery_no",
        "送货：修改送货单号（列表）",
        "delivery",
        "送货",
    ),
    ("delivery.action.edit_waybill", "送货：修改快递单号（列表）", "delivery", "送货"),
    ("delivery.api.customers_search", "送货：客户搜索接口", "delivery", "送货"),
    ("delivery.api.pending_items", "送货：待送明细接口", "delivery", "送货"),
    ("delivery.api.next_waybill", "送货：取单号接口", "delivery", "送货"),
    ("report_notes.page.view", "报表：送货单导出页", "report_notes", "报表导出"),
    ("report_notes.export.run", "报表：执行导出送货单", "report_notes", "报表导出"),
    ("report_records.page.view", "报表：送货记录导出页", "report_records", "报表导出"),
    (
        "report_records.export.run",
        "报表：执行导出送货记录",
        "report_records",
        "报表导出",
    ),
    ("express.action.company_create", "快递：新建快递公司", "express", "快递"),
    ("express.action.company_edit", "快递：编辑快递公司", "express", "快递"),
    ("express.action.waybill_import", "快递：单号池导入", "express", "快递"),
    ("express.action.waybill_batch_delete", "快递：单号池批量删除", "express", "快递"),
    (
        "inventory_query.filter.category",
        "库存查询：类别",
        "inventory_query",
        "库存查询",
    ),
    ("inventory_query.filter.spec", "库存查询：规格", "inventory_query", "库存查询"),
    (
        "inventory_query.filter.series",
        "库存查询：系列",
        "inventory_query",
        "库存查询",
    ),
    (
        "inventory_query.filter.name_spec",
        "库存查询：品名/规格/编号",
        "inventory_query",
        "库存查询",
    ),
    (
        "inventory_query.filter.storage_area",
        "库存查询：仓储区",
        "inventory_query",
        "库存查询",
    ),
    (
        "inventory_ops_finished.api.products_search",
        "成品录入：产品搜索接口",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.api.suggest_storage_area",
        "成品录入：仓储区建议接口",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.api.movement_line_on_hand",
        "成品录入：录入行当前结存接口",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.movement.list",
        "成品录入：库存批次列表",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.movement.create",
        "成品录入：手工出入库",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.movement.export",
        "成品录入：导出进出明细",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.movement.delete",
        "成品录入：删除进出明细",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.movement_batch.void",
        "成品录入：撤销手工/导入批次",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.opening.list",
        "成品录入：期初列表",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.opening.create",
        "成品录入：新建期初",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.opening.edit",
        "成品录入：编辑期初",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.opening.delete",
        "成品录入：删除期初",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.daily.list",
        "成品录入：日结列表",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.daily.create",
        "成品录入：新建日结",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.daily.detail",
        "成品录入：日结详情",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.daily.edit",
        "成品录入：编辑日结",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_finished.daily.delete",
        "成品录入：删除日结",
        "inventory_ops_finished",
        "成品录入",
    ),
    (
        "inventory_ops_semi.api.products_search",
        "半成品录入：产品搜索接口",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.api.suggest_storage_area",
        "半成品录入：仓储区建议接口",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.api.movement_line_on_hand",
        "半成品录入：录入行当前结存接口",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.movement.list",
        "半成品录入：库存批次列表",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.movement.create",
        "半成品录入：手工出入库",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.movement.export",
        "半成品录入：导出进出明细",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.movement.delete",
        "半成品录入：删除进出明细",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.movement_batch.void",
        "半成品录入：撤销手工/导入批次",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.opening.list",
        "半成品录入：期初列表",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.opening.create",
        "半成品录入：新建期初",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.opening.edit",
        "半成品录入：编辑期初",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.opening.delete",
        "半成品录入：删除期初",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.daily.list",
        "半成品录入：日结列表",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.daily.create",
        "半成品录入：新建日结",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.daily.detail",
        "半成品录入：日结详情",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.daily.edit",
        "半成品录入：编辑日结",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_semi.daily.delete",
        "半成品录入：删除日结",
        "inventory_ops_semi",
        "半成品录入",
    ),
    (
        "inventory_ops_material.api.products_search",
        "材料录入：产品搜索接口",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.api.suggest_storage_area",
        "材料录入：仓储区建议接口",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.api.movement_line_on_hand",
        "材料录入：录入行当前结存接口",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.movement.list",
        "材料录入：库存批次列表",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.movement.create",
        "材料录入：手工出入库",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.movement.export",
        "材料录入：导出进出明细",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.movement.delete",
        "材料录入：删除进出明细",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.movement_batch.void",
        "材料录入：撤销手工/导入批次",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.opening.list",
        "材料录入：期初列表",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.opening.create",
        "材料录入：新建期初",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.opening.edit",
        "材料录入：编辑期初",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.opening.delete",
        "材料录入：删除期初",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.daily.list",
        "材料录入：日结列表",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.daily.create",
        "材料录入：新建日结",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.daily.detail",
        "材料录入：日结详情",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.daily.edit",
        "材料录入：编辑日结",
        "inventory_ops_material",
        "材料录入",
    ),
    (
        "inventory_ops_material.daily.delete",
        "材料录入：删除日结",
        "inventory_ops_material",
        "材料录入",
    ),
    ("customer.filter.keyword", "客户列表：关键词搜索", "customer", "客户"),
    ("customer.action.create", "客户：新建", "customer", "客户"),
    ("customer.action.edit", "客户：编辑", "customer", "客户"),
    ("customer.action.delete", "客户：删除", "customer", "客户"),
    ("customer.action.import", "客户：Excel 导入", "customer", "客户"),
    # CRM
    ("crm_lead.action.create", "CRM 线索：新建", "crm_lead", "CRM"),
    ("crm_lead.action.edit", "CRM 线索：编辑", "crm_lead", "CRM"),
    ("crm_lead.action.delete", "CRM 线索：删除", "crm_lead", "CRM"),
    ("crm_opportunity.action.create", "CRM 机会：新建", "crm_opportunity", "CRM"),
    ("crm_opportunity.action.edit", "CRM 机会：编辑", "crm_opportunity", "CRM"),
    ("crm_opportunity.action.generate_order", "CRM 机会：生成订单", "crm_opportunity", "CRM"),
    ("crm_ticket.action.create", "CRM 工单：新建", "crm_ticket", "CRM"),
    ("crm_ticket.action.edit", "CRM 工单：编辑", "crm_ticket", "CRM"),
    ("crm_ticket.action.delete", "CRM 工单：删除", "crm_ticket", "CRM"),
    ("product.filter.keyword", "产品列表：关键词搜索", "product", "产品"),
    ("product.action.create", "产品：新建", "product", "产品"),
    ("product.action.edit", "产品：编辑", "product", "产品"),
    ("product.action.delete", "产品：删除", "product", "产品"),
    ("product.action.import", "产品：Excel 导入", "product", "产品"),
    ("company.action.create", "公司主体：新建", "company", "公司主体"),
    ("company.action.edit", "公司主体：编辑", "company", "公司主体"),
    ("company.action.delete", "公司主体：删除", "company", "公司主体"),
    ("user_mgmt.action.edit", "用户管理：编辑用户", "user_mgmt", "用户管理"),
    ("role_mgmt.action.create", "角色管理：新建角色", "role_mgmt", "角色管理"),
    ("role_mgmt.action.edit", "角色管理：编辑角色", "role_mgmt", "角色管理"),
    ("role_mgmt.action.delete", "角色管理：删除角色", "role_mgmt", "角色管理"),
    ("reconciliation.page.export", "对账：导出页", "reconciliation", "对账"),
    ("reconciliation.action.download", "对账：下载文件", "reconciliation", "对账"),
    ("openclaw.customers.read", "OpenClaw：客户列表", "customer", "OpenClaw"),
    (
        "openclaw.customer_products.read",
        "OpenClaw：客户产品列表",
        "customer_product",
        "OpenClaw",
    ),
    ("openclaw.pending_items.read", "OpenClaw：待发货明细", "delivery", "OpenClaw"),
    ("openclaw.order.create", "OpenClaw：创建订单", "order", "OpenClaw"),
    ("openclaw.delivery.create", "OpenClaw：创建送货单", "delivery", "OpenClaw"),
    ("openclaw.companies.read", "OpenClaw：经营主体列表", "customer", "OpenClaw"),
    ("openclaw.products.read", "OpenClaw：系统产品搜索", "product", "OpenClaw"),
    ("openclaw.customer.create", "OpenClaw：新建客户", "customer", "OpenClaw"),
    (
        "openclaw.customer_product.create",
        "OpenClaw：新建客户产品绑定",
        "customer_product",
        "OpenClaw",
    ),
    ("openclaw.order.preview", "OpenClaw：订单创建预览", "order", "OpenClaw"),
    ("openclaw.delivery.preview", "OpenClaw：送货单创建预览", "delivery", "OpenClaw"),
    ("hr_department.filter.keyword", "HR 部门：关键词", "hr_department", "人力资源"),
    ("hr_department.action.create", "HR 部门：新建", "hr_department", "人力资源"),
    ("hr_department.action.edit", "HR 部门：编辑", "hr_department", "人力资源"),
    ("hr_department.action.delete", "HR 部门：删除", "hr_department", "人力资源"),
    ("hr_work_type.action.create", "HR 工种：新建", "hr_work_type", "人力资源"),
    ("hr_work_type.action.edit", "HR 工种：编辑", "hr_work_type", "人力资源"),
    ("hr_work_type.action.delete", "HR 工种：删除", "hr_work_type", "人力资源"),
    ("hr_employee.filter.company", "HR 人员：按主体筛选", "hr_employee", "人力资源"),
    ("hr_employee.filter.keyword", "HR 人员：关键词", "hr_employee", "人力资源"),
    ("hr_employee.action.create", "HR 人员：新建", "hr_employee", "人力资源"),
    ("hr_employee.action.edit", "HR 人员：编辑", "hr_employee", "人力资源"),
    ("hr_employee.action.delete", "HR 人员：删除", "hr_employee", "人力资源"),
    ("hr_employee.action.import", "HR 人员：Excel 导入", "hr_employee", "人力资源"),
    (
        "hr_employee.action.export_template",
        "HR 人员：下载导入模板",
        "hr_employee",
        "人力资源",
    ),
    (
        "hr_employee.view_sensitive",
        "HR 人员：查看身份证/完整手机",
        "hr_employee",
        "人力资源",
    ),
    ("hr_payroll.view", "HR 工资：查看", "hr_payroll", "人力资源"),
    ("hr_payroll.edit", "HR 工资：录入与修改", "hr_payroll", "人力资源"),
    ("hr_payroll.export", "HR 工资：导出 Excel", "hr_payroll", "人力资源"),
    ("dept_piece_rate.view", "工种计件单价：查看", "dept_piece_rate", "人力资源"),
    ("dept_piece_rate.edit", "工种计件单价：编辑与删除", "dept_piece_rate", "人力资源"),
    ("hr_performance.action.create", "HR 绩效：新建", "hr_performance", "人力资源"),
    ("hr_performance.action.edit", "HR 绩效：编辑", "hr_performance", "人力资源"),
    ("hr_performance.action.delete", "HR 绩效：删除", "hr_performance", "人力资源"),
    ("hr_performance.action.finalize", "HR 绩效：定稿", "hr_performance", "人力资源"),
    (
        "hr_performance.action.override",
        "HR 绩效：已定稿后修改",
        "hr_performance",
        "人力资源",
    ),
    (
        "hr_employee_capability.view",
        "人员能力表：查看",
        "hr_employee_capability",
        "人力资源",
    ),
    (
        "hr_department_capability_map.view",
        "部门-工种允许关系：查看",
        "hr_department_capability_map",
        "人力资源",
    ),
    (
        "hr_department_capability_map.edit",
        "部门-工种允许关系：维护",
        "hr_department_capability_map",
        "人力资源",
    ),
    (
        "production.preplan.action.create",
        "预生产计划：新建",
        "production_preplan",
        "预生产计划",
    ),
    (
        "production.preplan.action.edit",
        "预生产计划：编辑",
        "production_preplan",
        "预生产计划",
    ),
    (
        "production.preplan.action.delete",
        "预生产计划：删除",
        "production_preplan",
        "预生产计划",
    ),
    (
        "production.calc.action.run",
        "预生产计划：生产测算运行",
        "production_preplan",
        "预生产计划",
    ),
    (
        "production.preplan.cost.view",
        "预生产计划：查看测算成本",
        "production_preplan",
        "预生产计划",
    ),
    (
        "orchestrator.replay.high_risk",
        "编排引擎：高风险重放",
        "production_preplan",
        "编排引擎运维",
    ),
    (
        "orchestrator.recover.batch",
        "编排引擎：批量恢复死信",
        "production_preplan",
        "编排引擎运维",
    ),
    (
        "orchestrator.metric.write",
        "编排引擎：写AI评估指标",
        "production_preplan",
        "编排引擎运维",
    ),
    (
        "production_incident.filter.keyword",
        "生产事故：关键词筛选",
        "production_incident",
        "生产事故",
    ),
    (
        "production_incident.action.create",
        "生产事故：新建",
        "production_incident",
        "生产事故",
    ),
    (
        "production_incident.action.edit",
        "生产事故：编辑",
        "production_incident",
        "生产事故",
    ),
    (
        "production_incident.action.delete",
        "生产事故：删除",
        "production_incident",
        "生产事故",
    ),
    (
        "production_incident.report.8d",
        "生产事故：8D 报告（打印/导出）",
        "production_incident",
        "生产事故",
    ),
    ("machine_type.action.create", "机台种类：新建", "machine_type", "机台管理"),
    ("machine_type.action.edit", "机台种类：编辑", "machine_type", "机台管理"),
    ("machine_type.action.delete", "机台种类：删除", "machine_type", "机台管理"),
    ("machine_asset.filter.keyword", "机台台账：关键词", "machine_asset", "机台管理"),
    ("machine_asset.action.create", "机台台账：新建", "machine_asset", "机台管理"),
    ("machine_asset.action.edit", "机台台账：编辑", "machine_asset", "机台管理"),
    ("machine_asset.action.delete", "机台台账：删除", "machine_asset", "机台管理"),
    (
        "machine_runtime.action.create",
        "机台运转：新建记录",
        "machine_runtime",
        "机台管理",
    ),
    (
        "machine_runtime.action.edit",
        "机台运转：编辑记录",
        "machine_runtime",
        "机台管理",
    ),
    (
        "machine_runtime.action.close",
        "机台运转：结束记录",
        "machine_runtime",
        "机台管理",
    ),
    (
        "machine_schedule_template.action.create",
        "机台排班：模板新建",
        "machine_schedule",
        "机台管理",
    ),
    (
        "machine_schedule_template.action.edit",
        "机台排班：模板编辑",
        "machine_schedule",
        "机台管理",
    ),
    (
        "machine_schedule_template.action.delete",
        "机台排班：模板删除",
        "machine_schedule",
        "机台管理",
    ),
    (
        "machine_schedule_booking.action.create",
        "机台排班：时间窗新建/生成",
        "machine_schedule",
        "机台管理",
    ),
    (
        "machine_schedule_booking.action.edit",
        "机台排班：时间窗编辑",
        "machine_schedule",
        "机台管理",
    ),
    (
        "machine_schedule_booking.action.delete",
        "机台排班：时间窗删除",
        "machine_schedule",
        "机台管理",
    ),
    (
        "hr_employee_schedule_template.action.create",
        "人员排产：模板新建",
        "hr_employee_schedule",
        "人力资源",
    ),
    (
        "hr_employee_schedule_template.action.edit",
        "人员排产：模板编辑",
        "hr_employee_schedule",
        "人力资源",
    ),
    (
        "hr_employee_schedule_template.action.delete",
        "人员排产：模板删除",
        "hr_employee_schedule",
        "人力资源",
    ),
    (
        "hr_employee_schedule_booking.action.create",
        "人员排产：时间窗新建/生成",
        "hr_employee_schedule",
        "人力资源",
    ),
    (
        "hr_employee_schedule_booking.action.edit",
        "人员排产：时间窗编辑",
        "hr_employee_schedule",
        "人力资源",
    ),
    (
        "hr_employee_schedule_booking.action.delete",
        "人员排产：时间窗删除",
        "hr_employee_schedule",
        "人力资源",
    ),
    (
        "procurement_material.filter.keyword",
        "物料管理：关键词",
        "procurement_material",
        "采购管理",
    ),
    (
        "procurement_material.action.create",
        "物料管理：新建",
        "procurement_material",
        "采购管理",
    ),
    (
        "procurement_material.action.edit",
        "物料管理：编辑",
        "procurement_material",
        "采购管理",
    ),
    (
        "procurement_material.action.delete",
        "物料管理：删除",
        "procurement_material",
        "采购管理",
    ),
    (
        "procurement_material.action.import",
        "物料管理：Excel 导入",
        "procurement_material",
        "采购管理",
    ),
    (
        "procurement_supplier.filter.keyword",
        "供应商：关键词",
        "procurement_supplier",
        "采购管理",
    ),
    (
        "procurement_supplier.action.create",
        "供应商：新建",
        "procurement_supplier",
        "采购管理",
    ),
    (
        "procurement_supplier.action.edit",
        "供应商：编辑",
        "procurement_supplier",
        "采购管理",
    ),
    (
        "procurement_supplier.action.delete",
        "供应商：删除",
        "procurement_supplier",
        "采购管理",
    ),
    (
        "procurement_requisition.filter.keyword",
        "采购请购：关键词",
        "procurement_requisition",
        "采购管理",
    ),
    (
        "procurement_requisition.action.create",
        "采购请购：新建",
        "procurement_requisition",
        "采购管理",
    ),
    (
        "procurement_requisition.action.edit",
        "采购请购：编辑",
        "procurement_requisition",
        "采购管理",
    ),
    (
        "procurement_requisition.action.delete",
        "采购请购：删除",
        "procurement_requisition",
        "采购管理",
    ),
    (
        "procurement_requisition.action.print",
        "采购请购：打印",
        "procurement_requisition",
        "采购管理",
    ),
    (
        "procurement_requisition.action.mark_signed",
        "采购请购：标记已签字",
        "procurement_requisition",
        "采购管理",
    ),
    (
        "procurement_requisition.action.generate_orders",
        "采购请购：生成采购单",
        "procurement_requisition",
        "采购管理",
    ),
    (
        "procurement_order.filter.keyword",
        "采购单：关键词",
        "procurement_order",
        "采购管理",
    ),
    (
        "procurement_order.action.create",
        "采购单：新建",
        "procurement_order",
        "采购管理",
    ),
    ("procurement_order.action.edit", "采购单：编辑", "procurement_order", "采购管理"),
    (
        "procurement_order.action.delete",
        "采购单：删除",
        "procurement_order",
        "采购管理",
    ),
    (
        "procurement_order.action.detail",
        "采购单：详情",
        "procurement_order",
        "采购管理",
    ),
    ("procurement_order.action.print", "采购单：打印", "procurement_order", "采购管理"),
    (
        "procurement_order.action.mark_ordered",
        "采购单：标记已下单",
        "procurement_order",
        "采购管理",
    ),
    (
        "procurement_receipt.filter.keyword",
        "采购收货：关键词",
        "procurement_receipt",
        "采购管理",
    ),
    (
        "procurement_receipt.action.create",
        "采购收货：新建",
        "procurement_receipt",
        "采购管理",
    ),
    (
        "procurement_receipt.action.edit",
        "采购收货：编辑",
        "procurement_receipt",
        "采购管理",
    ),
    (
        "procurement_receipt.action.delete",
        "采购收货：删除",
        "procurement_receipt",
        "采购管理",
    ),
    (
        "procurement_receipt.action.compare",
        "采购收货：查看对比",
        "procurement_receipt",
        "采购管理",
    ),
    (
        "procurement_receipt.action.approve_stockin",
        "采购收货：确认采购入库",
        "procurement_receipt",
        "采购管理",
    ),
    (
        "procurement_stockin.filter.keyword",
        "采购入库：关键词",
        "procurement_stockin",
        "采购管理",
    ),
)


def as_list() -> List[Tuple[str, str, str, str]]:
    return list(CAPABILITY_FALLBACK)
