"""与 run_16_seed_nav_capability.sql 一致；库表无数据时兜底。"""

from typing import List, Tuple

# (code, title, nav_item_code, group_label)
CAPABILITY_FALLBACK: Tuple[Tuple[str, str, str, str], ...] = (
    ("order.filter.customer", "订单列表：按客户筛选", "order", "订单"),
    ("order.filter.status", "订单列表：按状态筛选", "order", "订单"),
    ("order.filter.payment_type", "订单列表：按付款类型筛选", "order", "订单"),
    ("order.filter.keyword", "订单列表：关键词搜索", "order", "订单"),
    ("order.action.create", "订单：新建", "order", "订单"),
    ("order.action.edit", "订单：编辑", "order", "订单"),
    ("order.action.delete", "订单：删除", "order", "订单"),
    ("customer_product.filter.customer", "客户产品列表：按客户筛选", "customer_product", "客户产品"),
    ("customer_product.filter.keyword", "客户产品列表：关键词搜索", "customer_product", "客户产品"),
    ("customer_product.action.create", "客户产品：新建", "customer_product", "客户产品"),
    ("customer_product.action.edit", "客户产品：编辑", "customer_product", "客户产品"),
    ("customer_product.action.delete", "客户产品：删除", "customer_product", "客户产品"),
    ("customer_product.action.import", "客户产品：Excel 导入", "customer_product", "客户产品"),
    ("customer_product.action.export_template", "客户产品：下载导入模板", "customer_product", "客户产品"),
    ("delivery.filter.customer", "送货列表：按客户筛选", "delivery", "送货"),
    ("delivery.filter.status", "送货列表：按状态筛选", "delivery", "送货"),
    ("delivery.filter.keyword", "送货列表：关键词搜索", "delivery", "送货"),
    ("delivery.action.create", "送货：新建送货单", "delivery", "送货"),
    ("delivery.action.detail", "送货：详情", "delivery", "送货"),
    ("delivery.action.print", "送货：打印", "delivery", "送货"),
    ("delivery.action.mark_shipped", "送货：标记已发", "delivery", "送货"),
    ("delivery.action.mark_created", "送货：标记待发", "delivery", "送货"),
    ("delivery.action.mark_expired", "送货：标记失效", "delivery", "送货"),
    ("delivery.action.delete", "送货：删除", "delivery", "送货"),
    ("delivery.action.clear_waybill", "送货：清空快递单号", "delivery", "送货"),
    ("delivery.action.edit_delivery_no", "送货：修改送货单号（列表）", "delivery", "送货"),
    ("delivery.action.edit_waybill", "送货：修改快递单号（列表）", "delivery", "送货"),
    ("delivery.api.customers_search", "送货：客户搜索接口", "delivery", "送货"),
    ("delivery.api.pending_items", "送货：待送明细接口", "delivery", "送货"),
    ("delivery.api.next_waybill", "送货：取单号接口", "delivery", "送货"),
    ("report_notes.page.view", "报表：送货单导出页", "report_notes", "报表导出"),
    ("report_notes.export.run", "报表：执行导出送货单", "report_notes", "报表导出"),
    ("report_records.page.view", "报表：送货记录导出页", "report_records", "报表导出"),
    ("report_records.export.run", "报表：执行导出送货记录", "report_records", "报表导出"),
    ("express.action.company_create", "快递：新建快递公司", "express", "快递"),
    ("express.action.company_edit", "快递：编辑快递公司", "express", "快递"),
    ("express.action.waybill_import", "快递：单号池导入", "express", "快递"),
    ("inventory_query.filter.category", "库存查询：类别", "inventory_query", "库存查询"),
    ("inventory_query.filter.spec", "库存查询：规格", "inventory_query", "库存查询"),
    ("inventory_query.filter.name_spec", "库存查询：品名/规格/编号", "inventory_query", "库存查询"),
    ("inventory_query.filter.storage_area", "库存查询：仓储区", "inventory_query", "库存查询"),
    ("inventory_ops.api.products_search", "库存录入：产品搜索接口", "inventory_ops", "库存录入"),
    ("inventory_ops.api.suggest_storage_area", "库存录入：仓储区建议接口", "inventory_ops", "库存录入"),
    ("inventory_ops.movement.list", "库存录入：库存批次列表", "inventory_ops", "库存录入"),
    ("inventory_ops.movement.create", "库存录入：手工出入库", "inventory_ops", "库存录入"),
    ("inventory_ops.movement.delete", "库存录入：删除进出明细", "inventory_ops", "库存录入"),
    ("inventory_ops.movement_batch.void", "库存录入：撤销手工/导入批次", "inventory_ops", "库存录入"),
    ("inventory_ops.opening.list", "库存录入：期初列表", "inventory_ops", "库存录入"),
    ("inventory_ops.opening.create", "库存录入：新建期初", "inventory_ops", "库存录入"),
    ("inventory_ops.opening.edit", "库存录入：编辑期初", "inventory_ops", "库存录入"),
    ("inventory_ops.opening.delete", "库存录入：删除期初", "inventory_ops", "库存录入"),
    ("inventory_ops.daily.list", "库存录入：日结列表", "inventory_ops", "库存录入"),
    ("inventory_ops.daily.create", "库存录入：新建日结", "inventory_ops", "库存录入"),
    ("inventory_ops.daily.detail", "库存录入：日结详情", "inventory_ops", "库存录入"),
    ("inventory_ops.daily.edit", "库存录入：编辑日结", "inventory_ops", "库存录入"),
    ("inventory_ops.daily.delete", "库存录入：删除日结", "inventory_ops", "库存录入"),
    ("customer.filter.keyword", "客户列表：关键词搜索", "customer", "客户"),
    ("customer.action.create", "客户：新建", "customer", "客户"),
    ("customer.action.edit", "客户：编辑", "customer", "客户"),
    ("customer.action.delete", "客户：删除", "customer", "客户"),
    ("customer.action.import", "客户：Excel 导入", "customer", "客户"),
    ("product.filter.keyword", "产品列表：关键词搜索", "product", "产品"),
    ("product.action.create", "产品：新建", "product", "产品"),
    ("product.action.edit", "产品：编辑", "product", "产品"),
    ("product.action.delete", "产品：删除", "product", "产品"),
    ("product.action.import", "产品：Excel 导入", "product", "产品"),
    ("company.action.create", "公司主体：新建", "company", "公司主体"),
    ("company.action.edit", "公司主体：编辑", "company", "公司主体"),
    ("company.action.delete", "公司主体：删除", "company", "公司主体"),
    ("user_mgmt.action.edit", "用户管理：编辑用户", "user_mgmt", "用户管理"),
    ("role_mgmt.action.create", "角色管理：新建角色", "role_mgmt", "角色管理"),
    ("role_mgmt.action.edit", "角色管理：编辑角色", "role_mgmt", "角色管理"),
    ("role_mgmt.action.delete", "角色管理：删除角色", "role_mgmt", "角色管理"),
    ("reconciliation.page.export", "对账：导出页", "reconciliation", "对账"),
    ("reconciliation.action.download", "对账：下载文件", "reconciliation", "对账"),
    ("openclaw.customers.read", "OpenClaw：客户列表", "customer", "OpenClaw"),
    ("openclaw.customer_products.read", "OpenClaw：客户产品列表", "customer_product", "OpenClaw"),
    ("openclaw.pending_items.read", "OpenClaw：待发货明细", "delivery", "OpenClaw"),
    ("openclaw.order.create", "OpenClaw：创建订单", "order", "OpenClaw"),
    ("openclaw.delivery.create", "OpenClaw：创建送货单", "delivery", "OpenClaw"),
    ("openclaw.companies.read", "OpenClaw：经营主体列表", "customer", "OpenClaw"),
    ("openclaw.products.read", "OpenClaw：系统产品搜索", "product", "OpenClaw"),
    ("openclaw.customer.create", "OpenClaw：新建客户", "customer", "OpenClaw"),
    ("openclaw.customer_product.create", "OpenClaw：新建客户产品绑定", "customer_product", "OpenClaw"),
    ("openclaw.order.preview", "OpenClaw：订单创建预览", "order", "OpenClaw"),
    ("openclaw.delivery.preview", "OpenClaw：送货单创建预览", "delivery", "OpenClaw"),
)


def as_list() -> List[Tuple[str, str, str, str]]:
    return list(CAPABILITY_FALLBACK)
